site_name: "Darklit"
theme: "material"
pages:
- Home: 'index.md'
- NuSpeak Reference:
    - Basics: 'nsref.basics.md'
    - External: 'nsref.ext.md'
    - Behaviour: 'nsref.beh.md'
- Script Templates:
    - Condition: 'stemp.cond.md'
    - Effect: 'stemp.effect.md'
    - Behaviour: 'stemp.beh.md'
    - Spawner: 'stemp.spawner.md'
- Commands :
    - Game: 'commands.game.md'
    - Dev: 'commands.dev.md'
- Game Data:
    - gameObject: gameData/gameObject.md
    - net: gameData/net.md
    - time: gameData/time.md
    - transform: gameData/transform.md
    - __vmtest: gameData/__vmtest.md
    - spawner: gameData/spawner.md
    - Character: gameData/Character.md
    - brain: gameData/brain.md
    - legs: gameData/legs.md
    - Health: gameData/Health.md
    - Oxygen: gameData/Oxygen.md
    - Stamina: gameData/Stamina.md
    - World: gameData/World.md
extra:
  palette:
    primary: 'red'
    accent: 'cyan'

