site_name: "NuSpeak - FALLBACK"
pages:
- Home: 'index.md'
- NuSpeak Reference:
    - Basics: nsref/nsref.basics.md
    - Types: 
      - Entity: nsref/nsref.entity.md
      - Fiber: 'nsref/nsref.fiber.md'
      - Array: 'nsref/nsref.array.md'
      - Option: 'nsref/nsref.option.md'
      - Future: 'nsref/nsref.future.md'
    - Yielding: 'nsref/nsref.yield.md'
    - Loops: 'nsref/nsref.loops.md'
    - Routines:
      - Overview: 'nsref/nsref.routine.overview.md'
      - Operators: 'nsref/nsref.routine.operators.md'
      - Async vs Sync: 'nsref/nsref.routine.asyncvsync.md'
    - Intrinsics:
      - Math: 'nsref/nsref.intr.math.md'
      - Random: 'nsref/nsref.intr.random.md'
      - Debug: 'nsref/nsref.intr.debug.md'
      - String: 'nsref/nsref.intr.string.md'
    - External (Legacy): 'nsref/nsref.ext.legacy.md'
    - Behaviour (Legacy): 'nsref/nsref.beh.legacy.md'
    - Fibers (Legacy): 'nsref/nsref.fibers.legacy.md'
- Script Templates:
    - AOE: 'stemp.AOE.md'
    - Condition: 'stemp.cond.md'
    - Effect: 'stemp.effect.md'
    - Behaviour: 'stemp.beh.md'
    - Spawner: 'stemp.spawner.md'
- Json Templates:
    - Condition: 'jsontemp.cond.md'
- Commands :
    - Game: 'commands.game.md'
    - Dev: 'commands.dev.md'
- Game Data:
    - alteration: gameData/alteration.md
    - aoes: gameData/aoes.md
    - attack: gameData/attack.md
    - brain: gameData/brain.md
    - character: gameData/character.md
    - chest: gameData/chest.md
    - dk: gameData/dk.md
    - entity: gameData/entity.md
    - gameObject: gameData/gameObject.md
    - health: gameData/health.md
    - health: gameData/health.md
    - legs: gameData/legs.md
    - navigation: gameData/navigation.md
    - net: gameData/net.md
    - oxygen: gameData/oxygen.md
    - random: gameData/random.md
    - skills: gameData/skills.md
    - spawner: gameData/spawner.md
    - stamina: gameData/stamina.md
    - target: gameData/target.md
    - throw: gameData/throw.md
    - time: gameData/time.md
    - transform: gameData/transform.md
    - visual: gameData/visual.md
    - weakness: gameData/weakness.md
    - wielder: gameData/wielder.md
    - world: gameData/world.md
theme:
  name: 'material'
  logo:
    icon: 'developer board'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  palette:
    primary: 'cyan'
    accent: 'pink'
  feature:
    tabs: true
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
extra_css:
  - 'stylesheets/extra.css'

