site_name: "Darklit"
theme: "material"
pages:
- Home: 'index.md'
- NuSpeak Reference:
    - Basics: 'nsref.basics.md'
    - External: 'nsref.ext.md'
    - Behaviour: 'nsref.beh.md'
- Script Templates:
    - Condition: 'stemp.cond.md'
    - Effect: 'stemp.effect.md'
    - Behaviour: 'stemp.beh.md'
    - Spawner: 'stemp.spawner.md'
- Commands :
    - Game: 'commands.game.md'
    - Dev: 'commands.dev.md'
- Game Data:
    - gameObject: gameData/gameObject.md
    - net: gameData/net.md
    - random: gameData/random.md
    - time: gameData/time.md
    - transform: gameData/transform.md
    - __vmtest: gameData/__vmtest.md
    - spawner: gameData/spawner.md
    - attack: gameData/attack.md
    - Character: gameData/Character.md
    - brain: gameData/brain.md
    - weakness: gameData/weakness.md
    - legs: gameData/legs.md
    - aoe: gameData/aoe.md
    - throw: gameData/throw.md
    - health: gameData/health.md
    - Oxygen: gameData/Oxygen.md
    - stamina: gameData/stamina.md
    - Wieldable: gameData/Wieldable.md
    - World: gameData/World.md
extra:
  palette:
    primary: 'red'
    accent: 'cyan'

